# Use root/example as user/password credentials
version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  pictour:
    build: ./backend
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - mongo